site_name: ViVa-SAFELAND
site_url: https://viva-safeland.github.io/viva_safeland/
site_author: viva-safeland
site_description: >-
  A new freeware for safe validation of vision-based navigation in aerial vehicles.

# Repository
repo_name: viva-safeland/viva_safeland
repo_url: https://github.com/viva-safeland/viva_safeland

# Copyright
copyright: Copyright &copy; 2025 ViVa-SAFELAND

# Navigation 
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API Reference: api.md
  - About: about.md

# Theme
theme:
  name: material
  logo: assets/viva_logo.png
  favicon: assets/viva_logo.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.footer
    - content.code.copy
    - search.suggest
    - search.highlight
    - toc.follow
    - toc.integrate
    
  palette:
      primary: custom
      accent: deep orange

extra_css:
  - extra.css

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables

# Extra
extra:
  social:
    # - icon: simple/arxiv
    #   link: https://arxiv.org/abs/2503.14719
    - icon: simple/github
      link: https://github.com/viva-safeland/viva_safeland

# Plugins
plugins:
  - search
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          options:
            show_if_no_docstring: false
            group_by_category: true
            allow_inspection: true
            docstring_style: google
            show_source: false
            merge_init_into_class: true
            show_category_heading: false
            show_root_heading: false
            show_root_full_path: false
            find_stubs_package: true
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: table
